### PR TITLE
Replace merge with assign, address ember-polyfills.deprecate-merge

### PR DESCRIPTION
**Pull request by dbashford**
Getting deprecation notices from ember-spaniel in our app. This should fix it up.

Thanks!

### CODE REVIEW

**Comment by dbashford** [comment]
Possible for merge/publish on this? Any questions? Thanks!

**Comment by asakusuma** [comment]
Thanks!

**Comment by dbashford** [comment]
Thanks for the merge! Any chance of a quickie publish?

**Comment by asakusuma** [comment]
@dbashford `0.6.2` released

**Pull request merged**
