### PR TITLE
Add ability to configure Watcher options

### PR DESCRIPTION
**Pull request by backspace**
Hey, thanks for this, I was looking for something to [replace `Waypoints`](https://github.com/travis-ci/travis-web/pull/1422) as a step toward removing all of `travis-web`’s Bower dependencies.

I wanted to be able to configure `Watcher` as [described in the Spaniel documentation](https://linkedin.github.io/spaniel/interfaces/watcherconfig.html), so I added this interface. It seems like there aren’t tests for this but if I missed them, let me know, or if anything needs fixing.

### CODE REVIEW

**Comment by feanor07** [comment]
any plan about when the merge will be?

**Comment by asakusuma** [comment]
@backspace sorry for the way late response. I would prefer to have a separate method to create the watcher. I want to avoid the race condition where two different consumers of the service are trying to set their own options on the watcher.

**Comment by backspace** [comment]
That’s okay! Your desire makes sense to me. I ended up using another approach to replace Waypoints, but maybe someone else who needs this sort of functionality will produce a PR. 😀

**Comment by snewcomer** [comment]
I'm guessing this still needs some work.  To continuously watch the viewport?

**Pull request closed without merging**
