### PR TITLE
Move to yarn and upgrade

### PR DESCRIPTION
**Pull request by asakusuma**
Upgrade some build dependencies

### CODE REVIEW

**Comment by lynchbomb** [comment]
LG. I would also diff with the v1 branch of ember-spaniel as most of this has been complete within that release branch.

**Comment by scalvert** [comment]
Since we're moving to yarn we should probably delete package-lock.json. Also, does it make sense to upgrade this addon to the latest blueprint?

**Comment by asakusuma** [comment]
@scalvert this PR already deletes `package-lock.json`. What do you mean by...
> upgrade this addon to the latest blueprint

is blueprint some dependency?

**Comment by asakusuma** [comment]
Ok I've pulled in some additional upgrades from the v1 branch, and also the `nuke` command. I also did a rebase against v1 and the only merge conflicts are minor ones in `package.json` and the lock file. Merging.

**Comment by asakusuma** [comment]
Also, I tested the change in a few local apps

**Pull request merged**
